### PR TITLE
Normalize emails ending in @sms.ed.ac.uk to @ed.ac.uk and clarify some account activation things

### PR DESCRIPTION
**Pull request by mickzijdel**

### CODE REVIEW

**Comment by AlexMohanMD** [comment]
Will this absolutely work in all scenarios? I seem to remember emails in the format initial.last-name@sms.ed.ac.uk won't resolve without the sms portion. Some S-numbers don't resolve with sms though.

**Comment by AlexMohanMD** [comment]
Think edge cases, like custom aliases for people whose names have changed. Is there a very good reason to mess with the data integrity here?

**Comment by mickzijdel** [comment]
There is actually. I changed this because a lot of people this year (~10) received activation emails on s......@sms.ed.ac.uk , got confused and trying to reset their emails using the @ed.ac.uk and it cause a lot of issues. 

You do make a good point that for the initial.lastname@sms.ed.ac.uk it might mess it up. I'll ask a student to test. I'll have a quick look at adding a regex to only normalise s.......@ed.ac.uk style emails

**Comment by mickzijdel** [comment]
I am going to merge it now because some of these fixes are urgent, but happy to make further changes if needed.

**Pull request merged**
